In [ ]:
# Análise de dados eleitorais 2020

In [2]:
import pandas as pd
from tabulate import tabulate
import regex
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
base = pd.read_csv("dados/eleicoes-m-2020-twitter- tabela-completa.csv", sep=",", encoding="utf-8")
baseTw = pd.DataFrame(base[base['POSSUI TWITTER']=='S'])
base2T = pd.DataFrame(base[base['SEGUNDO TURNO']=='S'])
baseE = pd.DataFrame(base[base['ELEITO']=='S'])

# baseT.shape[0]
# list(base.columns)

# 'MUNICIPIO_ESTADO', 'NM_URNA_CANDIDATO', 'SG_PARTIDO', 'DS_COMPOSICAO_COLIGACAO', 'PORCENTAGEM_VOTOS_1_TURNO', 'QT_VOTOS_NOMINAIS', 'SEGUNDO TURNO', 'DT_NASCIMENTO', 'NR_IDADE_DATA_POSSE', 'DS_GENERO', 'DS_GRAU_INSTRUCAO', 'DS_ESTADO_CIVIL', 'DS_COR_RACA', 'DS_OCUPACAO', 'VR_DESPESA_MAX_CAMPANHA', 'POSSUI TWITTER', 'TWITTER LINK', 'USUÁRIO', 'ID', 'SEGUIDORES 01-11', 'SEGUIDORES 17-11', 'SEGUIDORES 29-11', 'TWEETS PUBLICADOS 01-11', 'TWEETS PUBLICADOS 17-11', 'TWEETS PUBLICADOS 29-11', 'BIO', 'NM_REGIAO', 'QTD_ELEITORES', 'QTD_ELEITORES_FEMININO', 'QTD_ELEITORES_MASCULINO', 'IDHM', 'IDHM_R', 'IDHM_L', 'IDHM_E'

In [4]:
# len(partidos.unique())
# len(municipios.unique())

idade = pd.DataFrame(base['NR_IDADE_DATA_POSSE'])
genero = pd.DataFrame(base['DS_GENERO'].value_counts(normalize=True)*100)
instrucao = pd.DataFrame(base['DS_GRAU_INSTRUCAO'].value_counts(normalize=True)*100)
estadoCivil = pd.DataFrame(base['DS_ESTADO_CIVIL'].value_counts(normalize=True)*100)
raca = pd.DataFrame(base['DS_COR_RACA'].value_counts(normalize=True)*100)
ocupacao = pd.DataFrame(base['DS_OCUPACAO'].value_counts(normalize=True)*100)
temTwitter = pd.DataFrame(base['POSSUI TWITTER'].value_counts(normalize=True)*100)
partidos = pd.DataFrame(base['SG_PARTIDO'].value_counts())
partidos.columns = ["Candidatos"]
municipios = pd.DataFrame(base['MUNICIPIO_ESTADO'].value_counts())
municipios.columns = ["Candidatos"]

# partidos.to_clipboard(sep='\t')
# municipios.to_clipboard(sep='\t')

In [99]:
idade.median()
genero.head(1)
instrucao.head(1)
estadoCivil.head(1)
raca.head(1)
ocupacao.head(1)
temTwitter.head(1)

NR_IDADE_DATA_POSSE    49.0
dtype: float64

In [5]:
idadeTw = pd.DataFrame(baseTw['NR_IDADE_DATA_POSSE'])
generoTw = pd.DataFrame(baseTw['DS_GENERO'].value_counts(normalize=True)*100)
instrucaoTw = pd.DataFrame(baseTw['DS_GRAU_INSTRUCAO'].value_counts(normalize=True)*100)
estadoCivilTw = pd.DataFrame(baseTw['DS_ESTADO_CIVIL'].value_counts(normalize=True)*100)
racaTw = pd.DataFrame(baseTw['DS_COR_RACA'].value_counts(normalize=True)*100)
ocupacaoTw = pd.DataFrame(baseTw['DS_OCUPACAO'].value_counts(normalize=True)*100)
partidosTw = pd.DataFrame(baseTw['SG_PARTIDO'].value_counts())
partidosTw.columns = ["Candidatos com Twitter"]
municipiosTw = pd.DataFrame(baseTw['MUNICIPIO_ESTADO'].value_counts())
municipiosTw.columns = ["Candidatos com Twitter"]

In [100]:
idadeTw.median()
generoTw.head(1)
instrucaoTw.head(1)
estadoCivilTw.head(1)
racaTw.head(1)
ocupacaoTw.head(1)
temTwitterTw.head(1)

NR_IDADE_DATA_POSSE    49.0
dtype: float64

In [6]:

distribuicaoCandidatosTw = pd.merge(partidos, partidosTw, left_index=True, right_index=True)
distribuicaoCandidatosTw['Candidatos sem Twitter'] = distribuicaoCandidatosTw['Candidatos'] - distribuicaoCandidatosTw['Candidatos com Twitter']

percentualCandidatosTw = distribuicaoCandidatosTw.copy()
percentualCandidatosTw['Candidatos sem Twitter'] = percentualCandidatosTw['Candidatos sem Twitter']/percentualCandidatosTw['Candidatos']

percentualCandidatosTw['Candidatos com Twitter'] = percentualCandidatosTw['Candidatos com Twitter']/percentualCandidatosTw['Candidatos']

percentualCandidatosTw = percentualCandidatosTw.drop(['Candidatos'], axis=1)

percentualCandidatosTw = percentualCandidatosTw.sort_values(by='Candidatos com Twitter', ascending=False)

percentualCandidatosTw

percentualCandidatosTw.to_clipboard(sep='\t')

               Candidatos com Twitter  Candidatos sem Twitter
PTB                          1.000000                0.000000
PROS                         1.000000                0.000000
PMN                          1.000000                0.000000
AVANTE                       1.000000                0.000000
PDT                          1.000000                0.000000
PSC                          1.000000                0.000000
PT                           1.000000                0.000000
DEM                          1.000000                0.000000
MDB                          0.923077                0.076923
PSDB                         0.916667                0.083333
PSOL                         0.909091                0.090909
REPUBLICANOS                 0.900000                0.100000
PSD                          0.888889                0.111111
NOVO                         0.888889                0.111111
PV                           0.875000                0.125000
PL                           0.857143                0.142857
PRTB                         0.857143                0.142857
PC do B                      0.833333                0.166667
REDE                         0.833333                0.166667
PSL                          0.833333                0.166667
PSB                          0.818182                0.181818
SOLIDARIEDADE                0.800000                0.200000
PP                           0.750000                0.250000
DC                           0.750000                0.250000
CIDADANIA                    0.714286                0.285714
PATRIOTA                     0.700000                0.300000
PODE                         0.700000                0.300000
PSTU                         0.625000                0.375000
UP                           0.500000                0.500000
PMB                          0.400000                0.600000
PTC                          0.333333                0.666667
PCO                          0.250000                0.750000

In [147]:
distribuicaoCandidatosTw = pd.merge(municipios, municipiosTw, left_index=True, right_index=True)
distribuicaoCandidatosTw['Candidatos sem Twitter'] = distribuicaoCandidatosTw['Candidatos'] - distribuicaoCandidatosTw['Candidatos com Twitter']

percentualCandidatosTw = distribuicaoCandidatosTw.copy()
percentualCandidatosTw['Candidatos sem Twitter'] = percentualCandidatosTw['Candidatos sem Twitter']/percentualCandidatosTw['Candidatos']

percentualCandidatosTw['Candidatos com Twitter'] = percentualCandidatosTw['Candidatos com Twitter']/percentualCandidatosTw['Candidatos']

percentualCandidatosTw = percentualCandidatosTw.drop(['Candidatos'], axis=1)

percentualCandidatosTw = percentualCandidatosTw.sort_values(by='Candidatos com Twitter', ascending=False)

percentualCandidatosTw

percentualCandidatosTw.to_clipboard(sep='\t')

                   Candidatos com Twitter  Candidatos sem Twitter
PORTO ALEGRE-RS                  1.000000                0.000000
SÃO PAULO-SP                     1.000000                0.000000
SALVADOR-BA                      1.000000                0.000000
RIO DE JANEIRO-RJ                1.000000                0.000000
SÃO LUÍS-MA                      1.000000                0.000000
BELO HORIZONTE-MG                0.933333                0.066667
GOIÂNIA-GO                       0.928571                0.071429
MANAUS-AM                        0.900000                0.100000
CUIABÁ-MT                        0.875000                0.125000
RIO BRANCO-AC                    0.857143                0.142857
NATAL-RN                         0.846154                0.153846
MACEIÓ-AL                        0.800000                0.200000
BOA VISTA-RR                     0.800000                0.200000
BELÉM-PA                         0.800000                0.200000
CURITIBA-PR                      0.800000                0.200000
JOÃO PESSOA-PB                   0.785714                0.214286
CAMPO GRANDE-MS                  0.769231                0.230769
PALMAS-TO                        0.750000                0.250000
TERESINA-PI                      0.750000                0.250000
ARACAJU-SE                       0.727273                0.272727
PORTO VELHO-RO                   0.714286                0.285714
FORTALEZA-CE                     0.700000                0.300000
VITÓRIA-ES                       0.692308                0.307692
RECIFE-PE                        0.666667                0.333333
FLORIANÓPOLIS-SC                 0.625000                0.375000

In [10]:
temTwitter = pd.DataFrame(base['POSSUI TWITTER'].value_counts(normalize=True)).transpose()
temTwitterE1T = pd.DataFrame(base[base['SEGUNDO TURNO']=='N'][base['ELEITO']=='S']['POSSUI TWITTER'].value_counts(normalize=True)).transpose()
temTwitter2T = pd.DataFrame(base[base['SEGUNDO TURNO']=='S']['POSSUI TWITTER'].value_counts(normalize=True)).transpose()
temTwitterE2T = pd.DataFrame(base[base['SEGUNDO TURNO']=='S'][base['ELEITO']=='S']['POSSUI TWITTER'].value_counts(normalize=True)).transpose()
temTwitterE = pd.DataFrame(base[base['ELEITO']=='S']['POSSUI TWITTER'].value_counts(normalize=True)).transpose()

percentualTwitter = pd.concat([temTwitter, temTwitterE1T, temTwitter2T, temTwitterE2T, temTwitterE])

percentualTwitter.to_clipboard(sep='\t')

temTwitter
temTwitterE1T
temTwitter2T
# temTwitterE2T
# temTwitterE

D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.

                       S         N
POSSUI TWITTER  0.830389  0.169611

                       S         N
POSSUI TWITTER  0.857143  0.142857

                       S         N
POSSUI TWITTER  0.888889  0.111111

In [ ]:
# exemplo filtro isin
# filtroVotacao = votacao[(votacao.MUNICIPIO_ESTADO.isin(["CUIABÁ-MT", "GOIÂNIA-GO", "NATAL-RN", "PALMAS-TO", "BELO HORIZONTE-MG", "ARACAJU-SE", "MANAUS-AM", "CURITIBA-PR", "SÃO PAULO-SP", "JOÃO PESSOA-PB", "BOA VISTA-RR", "PORTO VELHO-RO", "SÃO LUÍS-MA", "SALVADOR-BA", "FORTALEZA-CE", "VITÓRIA-ES", "RECIFE-PE", "MACEIÓ-AL", "MACAPÁ-AP", "BELÉM-PA", "RIO DE JANEIRO-RJ", "CAMPO GRANDE-MS", "RIO BRANCO-AC", "FLORIANÓPOLIS-SC", "TERESINA-PI", "PORTO ALEGRE-RS"]))&(votacao.DS_CARGO=='Prefeito')&(votacao.NR_TURNO==1)&(votacao.DS_DETALHE_SITUACAO_CAND.isin(["DEFERIDO","DEFERIDO COM RECURSO"]))]

# filtroVotacao2 = filtroVotacao.groupby(['NM_URNA_CANDIDATO']).agg({'MUNICIPIO_ESTADO': 'first','QT_VOTOS_NOMINAIS':'sum'})
# filtroVotacao2.to_csv("dados/votacao-prefeitos-capitais-4.csv", sep=";", encoding="iso-8859-1")